### ISSUE TITLE
runner does not pick up the prettier configs

### ISSUE THREAD

**Issue by DanielMSchmidt** [keplersj/jest-runner-prettier#87] opened 2018-08-23 16:41 UTC
I have a project with a `.prettierrc` and a `.prettierignore` and both of them are not being picked up. A PR adding [jest-runner-prettier](https://github.com/DanielMSchmidt/apollo-opentracing/pull/6) is failing, I think the problem is in this project. I wonder why, because I saw `prettier.resolveConfig` in your code, that should basically have done the trick, right?

**Comment by abraham** [comment] 2020-07-04 21:20
Running into the same issue.

**Comment by abraham** [comment] 2020-07-04 22:02
You can work around `.prettierignore` with `testPathIgnorePatterns`:

```js
// jest.config.js
module.exports = {
  projects: [
    {
      displayName: 'Prettier',
      preset: 'jest-runner-prettier',
      testPathIgnorePatterns: ['/node_modules/', '/dist/', '/package-lock.json/'],
    },
  ],
};
```

**Comment by drewlustro** [comment] 2022-03-05 01:07
Yeah, it's not picking up prettier config. Runner reports expected/got diff's that don't exist.

**Comment by keplersj** [comment] 2022-03-11 05:51
Hi all,

I'm having trouble recreating this issue. I've configured a few test cases with a `.prettierrc.json` file from the Prettier documentation and am getting correct errors from the test runner.

Would someone mind sharing a test configuration that replicates this issue?

Thanks!

**Comment by drewlustro** [comment] 2022-03-11 08:00
@keplersj – It's a monorepo. Now that I think about it, it's probably because there's multiple `.prettierrc.js` files. Generally, it looks like this:

```sh
frontend/app-foo/package.json  (contains jest-runner-prettier)
frontend/app-foo/.prettierrc.js
frontend/app-foo/jest.config.js  
frontend/app-foo/src
.prettierrc.js
```

The jest spec in question is (incorrectly) finding a diff in files under `frontend/app-foo/src`.

```js
// frontend/foo-app/.prettierrc.js  (correct one to use that it's not using)
module.exports = {
  printWidth: 80,
  trailingComma: 'all',
  singleQuote: true,
  bracketSameLine: false,
};
```

```js
// .prettierrc.js  (at root, prettier@1.x)
module.exports = {
  printWidth: 80,
  trailingComma: 'all',
  singleQuote: true,
  jsxBracketSameLine: false,
};
```

Come to think of it... this is likely the problem. Jest is executing with `rootDir` higher up than it should, and the runner is acquiring the prettierrc at monorepo root.

🤦 

Will confirm tomorrow.

**Comment by chripi** [comment] 2022-04-06 20:16
Any update on this issue? We are also looking at using this plugin to run prettier, but the fact that it does not pick up .prettierignore configs is blocking us from moving fwd. Thanks!

**Comment by drewlustro** [comment] 2022-04-16 00:11
Confirmed – in my project, _misconfigured jest_ was to blame.

Be sure that Jest's understanding of `rootDir` is appropriate (although I'm not sure that would guarantee good behavior).

Our application was picking up `.prettierrc.js` at root, instead of `frontend/app-name/.prettierrc.js`

**Comment by keplersj** [comment] 2022-04-16 02:10
Perfect. Gonna go ahead and close this issue. Thanks @drewlustro!

**Closed by keplersj** 2022-04-16 02:10 UTC
